# Generated by Django 4.2.4 on 2023-09-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='deepLink',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
